language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "zruzicka-github"

jdk:
  - oraclejdk8

script:
  - mvn -f MongoBasic/pom.xml test -DMONGO_USER=%MONGO_USER% -DMONGO_PASS=%MONGO_PASS%
  # JaCoCo is used to have code coverage, the agent has to be activated.
  # - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  # Just trying to execute additional scripts via Travis CI by the same build.
  - mvn -v 

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
  email:
    recipients:
      - zruzicka2@gmail.com
    on_success: never # default: change
    on_failure: always # default: always